### ISSUE TITLE
DefaultMatchStrategy does not exist

### ISSUE THREAD

**Issue by kanes115** [joken-elixir/joken_jwks#14]
Unfortunately there's no [DefaultMatchStrategy module](https://github.com/joken-elixir/joken_jwks/blob/master/lib/joken_jwks/default_strategy_template.ex#L55) nowhere in the repo.

**Comment by victorolinasc** [comment]
Hey @kanes115 ! Sorry about that... it is a typo/wrong module in the docs... 

THe correct one is this: https://hexdocs.pm/joken_jwks/JokenJwks.DefaultStrategyTemplate.html#content

I have to update the docs there. Thanks for pointing out

**Comment by kanes115** [comment]
Yes, I know it's a docs issue :) Thanks

**Comment by victorolinasc** [comment]
Fixed on 1.4.0.

Thanks once again for pointing it out @kanes115
