### ISSUE TITLE
JokenJwks.DefaultStrategy module does not exist

### ISSUE THREAD

**Issue by brweber2** [joken-elixir/joken_jwks#2]
The examples in the documentation refer to the `JokenJwks.DefaultStrategy` module, but it does not exist in the project.

**Comment by victorolinasc** [comment]
Thanks! That was my mistake! I am planning a thorough pass on docs soon. The correct module is `JokenJwks.DefaultStrategyTemplate`. Sorry for the confusion.

**Comment by lwhorton** [comment]
i can add a few things as i come up with them:

- this [function](https://github.com/joken-elixir/joken_jwks/blob/master/lib/joken_jwks/default_strategy_template.ex#L54) should read `init_opts` instead of `init`

**Comment by victorolinasc** [comment]
@bforchhammer wade an awesome PR about documentation and I really hope things improved. I'll be closing this for now. Please, re-open if there still are issues
