### ISSUE TITLE
'alg' is required, but should be optional

### ISSUE THREAD

**Issue by brweber2** [joken-elixir/joken_jwks#3]
According to the specs, 'alg' should technically be optional, but it is required in this library. 

Microsoft (both v1 and v2) jwks files do not include "alg" on the keys, instead they have "kty" of "RSA".

See the v2 url as an example: [https://login.microsoftonline.com/common/discovery/v2.0/keys](https://login.microsoftonline.com/common/discovery/v2.0/keys)

**Comment by victorolinasc** [comment]
You are right! I've missed that part. Will need to have that as a hook option. I just don't have the time to do that right now but as soon as I can I'll do that. 

Thanks for bringing that up!

**Comment by victorolinasc** [comment]
Fix incoming on #5
