### ISSUE TITLE
Upgrade `hackney` dependency

### ISSUE THREAD

**Issue by cgrothaus** [joken-elixir/joken_jwks#56]
This library locks down the `hackney` dependency to `~> 1.17.4 or ~> 1.18.0`. This prevents our application from using newer versions of Hackney (current version is `1.20.1`).

Please add newer versions to the constraint.

**Comment by victorolinasc** [comment]
So, just confirmed that the `override: true` flag on the dependency works as expected. You can upgrade `:hackney` with current version `~> "1.6"`  normally. I will merge the PR and keep testing for the other changes, but I am not hard pressed to release a new version.

Either way, thanks to bringing this up!
