### ISSUE TITLE
Support for content-type = 'application/jwk-set+json'

### ISSUE THREAD

**Issue by hjalet** [joken-elixir/joken_jwks#7]
Some OIDC providers specifies the content type = 'application/jwk-set+json' when returning the jwks document.
This means that the returned document will not be decoded to an elixir map, since the Tesla.JSON middleware is not made aware of this content-type, which again results in an error when trying to read the jwks document.

An example of an OIDC provider using this content-type can be found below:
https://demo.identityserver.io/.well-known/openid-configuration/jwks

A solution could be to pass the 'application/jwk-set+json' to the Tesla.JSON middleware as a content-type to be decoded as JSON.

**Comment by victorolinasc** [comment]
Nice feature to have for sure!

I can't work on it right now but PRs are highly appreciated. If you don't have the time now, I might get into this in the near future.

**Comment by hjalet** [comment]
Sounds good, I have created a PR for this.

**Comment by victorolinasc** [comment]
Thanks @hjalet ! Left some comments on your PR and once we address them we are good to go.

**Comment by victorolinasc** [comment]
This is merged. WIll release a minor version now.
