### ISSUE TITLE
Hackney version needs updated to fix HTTPS key retrieval

### ISSUE THREAD

**Issue by jonryser** [joken-elixir/joken_jwks#8]
Related: benoitc/hackney#591

The fix has been in the Hackney code for a couple of days, but an actual release was just made.  Proposing we update the version dependency in `mix.exs` to read `{:hackney, "~> 1.15.2"}`.

**Comment by ltj** [comment]
Created PR #9

**Comment by victorolinasc** [comment]
Thanks for your PR! I'll take a closer look at it in a moment.

Just to note that you can override the dep with `{:hackney, "~> 1.15.2", override: true}` in your mix.exs. That should work too without a new release.

I will, of course, bump the dep once I get the time to test it properly.

Thanks a lot for letting us know about the issue on hackney!

**Comment by victorolinasc** [comment]
There was not much to test :)

Thanks again for your PR @ltj
